language: android

sudo: false

jdk:
  - oraclejdk8

# we need the following license copying, cause travis fails to cooperate with android licenses
# just so you know, those are not my licenses. Somebody posted them on StackOverflow.

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-preview-license'
  - 'android-sdk-license-.+'
  - 'android-sdk-license'
  - 'google-gdk-license-.+'

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
   - $HOME/.gradle

